### PR TITLE
[ADD] mpc: Add l10n_cr_currency_rate_live module

### PR DESCRIPTION
**Pull request by JoseIbarraHdz**

### CODE REVIEW

**Comment by edy1192** [comment]
@JoseIbarraHdz you need to solve the conflicts here.

It would help if you did this in your GitHub repository:

- Change to stable branch: `git checkout 18.0`
- Update the stable branch: `git pull origin 18.0`
- Change to your dev branch and do a rebase: `git rebase -i origin/18.0`

I'd expect to see just one commit here.

**Comment by aMonroyL** [comment]
@JoseIbarraHdz whats missing for merging ?

**Comment by JoseIbarraHdz** [comment]
Hi @aMonroyL I already solved the conflicts, if @edy1192 give us her approval, this PR can be merge

**Comment by edy1192** [comment]
@JoseIbarraHdz @aMonroyL LGTM 👍🏼 

@hugho-ad could you merge this, please?

Regards.

**Comment by aMonroyL** [comment]
Thanks 2 all

**Pull request merged**
