### PR TITLE
[IMP] mpc: Add pricelists per sale order line T#86335 

### PR DESCRIPTION
**Pull request by VEscaname**
[MR](https://git.vauxoo.com/vauxoo/mpc/-/merge_requests/6)

Task [T#86335](https://www.vauxoo.com/web#id=86335&cids=1&model=project.task&view_type=form)

### CODE REVIEW

**Comment by aMonroyL** [comment]
@VEscaname pls notify when ready

**Comment by VEscaname** [comment]
@aMonroyL This is updated with the latest changes

**Comment by aMonroyL** [comment]
@CarmenMiranda pls push or request to Hugo if we have your +1

**Comment by CarmenMiranda** [comment]
> @CarmenMiranda pls push or request to Hugo if we have your +1

Hi @hugho-ad I already merged this one in GitLab, but I don't have the permission here, and here they don't have the merge of the [previous MR](https://git.vauxoo.com/vauxoo/mpc/-/merge_requests/5)

**Pull request merged**
